name: Build and Push Docker Images
on: 
 push:
 schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '11 11 1 * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Log in to GHCR
        uses: docker/login-action@v3  # Updated to v3 to fix warnings
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: qbdown/b3:latest,qbdown/b3:${{ github.run_number }}
